name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *' # Run nightly at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.2
      with:
    # Compiler to install
        compiler: g++-11

    - name: Compile
      run: |
        g++ main.cpp -o oneclickappinstaller_nightly.sh -Wall
        mv oneclickappinstaller_nightly.sh .github/compiled/oneclickappinstaller_nightly.sh

    - name: Update nightly release
      uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: .github/compiled/*.*
