name: Nightly Build

on:
  schedule:
    - cron: '0 0 * * *' # Run nightly at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up WSL
      uses: crazy-max/ghaction-wsl@v2
      with:
        dist: '22.04'

    - name: Compile
      run: |
        wsl g++ main.cpp -o oneclickappinstaller_nightly.sh -Wall
        g++ main.cpp -o oneclickappinstaller_nightly.exe -Wall
        
